name: Build Java App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Pobranie kodu
      - name: Checkout repository
        uses: actions/checkout@v4

      # Instalacja JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      # Budowa projektu Mavenem
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Przechowanie artefaktu JAR
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar
